return {
	Class = "Stance",
	Name = "Advanced",
	WeaponType = "Katana",
	BaseDamage = 15,
	BaseStaminaCost = 8,

	M1 = {
		[1] = {
			HitboxType = "Raycast", 
			HitboxDelay = 0.47,
		},

		[2] = {
			HitboxType = "Raycast", 
			HitboxDelay = 0.47,
		},

		[3] = {
			HitboxType = "Raycast", 
			HitboxDelay = 0.47,
		},

		[4] = {
			HitboxType = "Raycast", 
			HitboxDelay = 0.47,
		},
		[5] = {
			HitboxType = "Raycast", 
			HitboxDelay = 0.47,
		},
	},

	M2 = {
		Hits = {
			{	
				HitboxType = "Raycast", 
				HitboxDelay = 0.56, 
			},
		},
	},
}
