return {
	Name = "SamuraiHelmet",
	Class = "Equipable",
	Type = "Head",

	DisplayName = "Samurai Helmet",
	Description = `A helmet made for the samurai. \n • <font color="rgb(82,255,0)">5 Health</font> \n • <font color="rgb(255,242,0)">-2 Run Speed</font> \n • <font color="rgb(0,148,255)">-3 Stamina</font>`,

	MaxHealthIncrease = 5,
	MaxStaminaIncrease = -3,
	RunspeedIncrease = -2,

	MetalArmor = true,
	Rarity = "Rare",

	MaxStack = 1,
}
