return {
	Lifes = {
		["1"] = {
			AttackDistance = 6,
			TargetOffset = 3,
			DetectionDistance = 25,
			MaintainDistance = 45,
			RunDistance = 10,

			MaxDistanceFromSpawn = 50,

			ActionDistance = 11,
			ActionChance = 30,
			DeflectChance = 70,
			RollChance = 30,

			RunSpeed = 15,

			Actions = {
				"Run",
			},
		},
	},

	Equipment = {
		Weapon = {"BasicKatana",},
		Head = { "None", "None", "None", "PoliceHat" },
		Torso = {"PoliceShirt"},
		Legs = { "PolicePants" },
	},
}
