return {
	Lifes = {
		["2"] = {
			Health = 1000,
			AttackDistance = 6,
			TargetOffset = 3,

			MaintainDistance = 50,
			DetectionDistanceFromSpawn = 35,
			MaxDistanceFromSpawn = 100,

			ActionDistance = 11,
			ActionChance = 70,
			DeflectChance = 100,
			RollChance = 0,

			SkillChance = 10,

			Actions = {},
			Skills = {
				"Barrage",
				"FloatingPassage",
				"MoltenSmash",
			},
		},

		["1"] = {
			Health = 750,
			AttackDistance = 6,
			TargetOffset = 3,

			MaintainDistance = 50,
			DetectionDistanceFromSpawn = 35,
			MaxDistanceFromSpawn = 100,

			ActionDistance = 11,
			ActionChance = 85,
			DeflectChance = 100,
			RollChance = 0,

			SkillChance = 40,

			Actions = {},

			Skills = {
				"FloatingPassage",
				"Barrage",
				"MoltenSmash",
			},
		},
	},

	Equipment = {
		Weapon = { "Everflame" },
		Torso = { "InfernalChestguard" },
		Legs = { "InfernalLegguard" },
	},
}
