return {
	Name = "SamuraiLegplate",
	Class = "Equipable",
	Type = "Legs",

	DisplayName = "Samurai Legplate",
	Description = `A legplate made for the samurai. \n • <font color="rgb(82,255,0)">10 Health</font> \n • <font color="rgb(255,242,0)">-1 Run Speed</font> \n • <font color="rgb(0,148,255)">-5 Stamina</font>`,

	MaxHealthIncrease = 10,
	MaxStaminaIncrease = -5,
	RunspeedIncrease = -1,

	MetalArmor = true,

	Rarity = "Rare",

	MaxStack = 1,
}
