return {
	FreePoints = 0,
	UnlockedNodes = {},

	OtherSkills = {},

	Level = 1,
	Exp = 0,
	Tetsu = 0,

	Gamepass = {},



	Equipped = {
		Weapon = nil,
		Head = nil,
		Face = nil,
		Torso = nil,
		Legs = nil,
		Back = nil,
		Waist = nil,
		Prosthetic = nil,
	},

	RaceVariant = 1,

	Bounty = 0,
	Reputation = 0,

	UnlockedRugs = {},

	NPCs = {},

	UnlockedBlueprints = {},
	Quest = {},
	Hotbar = {},
	Inventory = {},

	SelectedStance = "Beginner",
	Stances = {
		"Beginner",
	},

	Settings = {
		Shadows = true,
		LowGraphics = false,
		AnimationsInfluence = true,
		CameraShake = true,
		CameraTilt = true,
		Waves = true,
		FovEffects = true,
		ScreenParticles = true,
		FollowCamera = true,
		LagCompensation = true,
		BloodFX = true,

		Ambience = true,
	},

}
