return {
	FreePoints = 0,
	UnlockedNodes = {},

	OtherSkills = {},

	Level = 1,
	Exp = 0,
	Tetsu = 0,
	Wisdom = 0,
	KillStreak = 0,

	Gamepass = {},

	Prison = {
		Labor = {
			AmountToCollect = 0,
			Collected = 0,
		},

		PrisonTime = 0,
	},

	Equipped = {
		Weapon = nil,
		LeftWeapon = nil,
		Head = nil,
		Face = nil,
		Torso = nil,
		Legs = nil,
		Back = nil,
		Waist = nil,
		Prosthetic = nil,
	},

	RaceVariant = 1,

	Bounty = 0,
	Reputation = 0,

	UnlockedRugs = {},
	SpawnRug = "",

	NPCs = {},

	UnlockedBlueprints = {},
	Quest = {},
	Hotbar = {},
	Inventory = {},

	SelectedStance = "Beginner",
	Stances = {
		"Beginner",
	},

	Settings = {
		Shadows = true,
		LowGraphics = false,
		AnimationsInfluence = true,
		CameraShake = true,
		CameraTilt = true,
		Waves = true,
		FovEffects = true,
		ScreenParticles = true,
		FollowCamera = true,
		LagCompensation = true,
		BloodFX = true,

		Ambience = true,
		OST = true,
	},

	Realm = {
		Removable = {},
		PlacedObjects = {},
	},
}
